CREATE DATABASE IF NOT EXISTS TODO

USE TODO

CREATE TABLE IF NOT EXISTS Tasks (
    id INT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    dueDate DATETIME
);