name: Docker Image CI to upload DB image

on:
  push:
    branches: ["i200469"]
  pull_request:
    branches: ["i200469","main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build the Docker image
        run: |
          cd src/db 
          docker build . --file Dockerfile --tag mlopsmystics:latest

      - name: Push Docker iamge
        run: |
          docker tag mlopsmystics:latest ${{ secrets.DOCKER_USERNAME }}/ca4_db:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/ca4_db:latest
